apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::631919637519:role/eksctl-expense-nodegroup-expense-NodeInstanceRole-xB4gpsiHDkFC
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - default-trainee
      userarn: arn:aws:iam::631919637519:user/suresh
      username: suresh
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-24T12:56:27Z"
  name: aws-auth
  namespace: kube-system
  uid: 78148694-7e88-4036-8c00-14295b9f7282